# Generated by Django 2.0.7 on 2019-03-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20190316_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=6, primary_key=True, serialize=False),
        ),
    ]
