# Generated by Django 2.0.7 on 2019-03-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20190318_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
