# Generated by Django 2.0.7 on 2019-03-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20190318_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nid',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
