# Generated by Django 2.0.7 on 2019-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
