# Generated by Django 2.0.7 on 2019-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20190325_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(auto_created=True, default='2019-04-01'),
        ),
    ]
