# Generated by Django 2.0.7 on 2019-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_auto_20190325_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
