# Generated by Django 2.0.7 on 2019-03-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_auto_20190325_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='host',
        ),
        migrations.AddField(
            model_name='token',
            name='host_user_bind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='audit.HostUserBind'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
