# Generated by Django 2.0.7 on 2019-03-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_auto_20190328_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_id',
            new_name='task',
        ),
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together={('task', 'host_user_bind')},
        ),
    ]
