# Generated by Django 2.0.7 on 2019-03-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_auto_20190331_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='task',
            new_name='task_id',
        ),
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together={('task_id', 'host_user_bind')},
        ),
    ]
